### ISSUE TITLE
ModuleTweakableDockingNode Issues

### ISSUE THREAD

**Issue by jsolson** [linuxgurugamer/TweakableEverything#3]
The forums went all internal server error on me while I was replying to you, so I'm posting here.

With the dll from yesterday, it's not screwing with attach nodes anymore, so in that sense it's good. The expected behavior if I've got it right is when a docking node has deployAnimationController set, and it has a referenceAttachNode, that node will be hidden when the animation indicates the port is shielded. I can't actually find a part that meets those conditions, but with parts that have animations not referenced by the docking node the attach nodes are left alone.

I'm seeing behavior that seems wrong though. On ports with a deployAnimationController the sliders for the other settings are all initialized and the "snap lock"/roll angles are set to 90, but on all other ports the Max capture/acquire roll angle are both 180, and all the others read -1. Seems like collateral damage but I'm not sure what it did before.

**Comment by linuxgurugamer** [comment]
FYI, the forums are back now.
The only thing I changed was checking to see if the animation was a deployAnimationController.  
So it seems that I need to check the initialization for the others.
Ok, not too difficult, thanks for getting back to me

**Comment by linuxgurugamer** [comment]
Fixed, will post back in the forum with a test dll
