### ISSUE TITLE
Commit 0402c70 has unstated changes which disabled some very useful features

### ISSUE THREAD

**Issue by 8749236** [linuxgurugamer/TweakableEverything#4]
Commit in question: 0402c700504fc80c8fede75219a0759d56db0f84

That commit specified that it added license.
However, it also disabled the gimbal range slider in Tweakable Gimbal module.
Is that an intentional change?

See line 48 and 103 of ModuleTweakableGimbal.cs.

I personally find that is a very useful feature and pretty much why I uses Tweakable everything since it allow players to control gimbals by degrees, instead of a percentage; which is harder to gauge its effect to gimbal. Also it allows player to increase gimbal to at most 200%

Note: this means gimbal range slider as advertised is absent.

**Comment by linuxgurugamer** [comment]
I don't really remember, but I can put it back.

**Comment by linuxgurugamer** [comment]
I'll need to test it, look for it in a day or so

**Comment by 8749236** [comment]
I checked the code, and I find it happened when you took over the project.
I did not find any other changes outside of the module in question that disabled the feature.
I think it should be easy.
And of course, take your time to test it and make sure it works fine.
Thank you.

**Comment by linuxgurugamer** [comment]
Oh, it was me.  I think that I saw there was a conflict with another 
mod, but that mod hasn't been updated since 0.24.  I was dealing with a 
lot with that mod, it was one of the more complicated mods I've taken, 
and has a strange way of being built.

Anyway, either tonight or tomorrow, I'm busy with a huge memory leak in 
another mod.  Have a solution, but need to get it working correctly.


LGG

**Comment by 8749236** [comment]
I wish you luck, with that memory leak. It  is notoriously hard to fix.

-----Original Message-----

**Comment by linuxgurugamer** [comment]
Oh, it's been found, and I released a 99% fix last night.

It's now a matter of doing it in a better way.

Thanks

**Comment by 8749236** [comment]
Update, it appears feature are back, but for some reason all gimbals setting starts with 0 instead of default value.
Effectively disables gimbal on all engine...
Version 0.1.19.1, commit 321913b

I noticed variable `gimbalRange` (declared on line 53) was never initialized to hold default value. (IIRC, C# initializes integers to 0 by default.)

**Comment by linuxgurugamer** [comment]
Strange, it's supposed to, I'll see if I can fix it now

**Comment by linuxgurugamer** [comment]
will be fixed in next relase today
